# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c0460629b043b0d10dd467f84994eb00032206417e8a23920c65076429b049e03237049ff0db78c9bc719abe4083c4efeb89fb7dafd468847c751db80af881

test:
  secret_key_base: 093a0aea94ed95ec00e7301b1b6508fa86d549e207139528d2a83bf4b43a33aca1535bb3b054162adc7e6cdc47dded56feee307d903c99864d3575c461773467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
